### ISSUE TITLE
Issues in Serious Sam HD

### ISSUE THREAD

**Issue by vlad54rus** [bibendovsky/eaxefx#10]
EAX effects in Serious Sam HD (both The First Encounter and The Second Encounter) stopped working since version 1.0.4.
I get this in the log file:

> [2021-06-14 15:47:56.640] [EAXEFX] [I]
> [2021-06-14 15:47:56.640] [EAXEFX] [I] <<<<<<<<<<<<<<<<<<<<<<<<
> [2021-06-14 15:47:56.640] [EAXEFX] [I] EAXEFX v1.0.6
> [2021-06-14 15:47:56.640] [EAXEFX] [I] ------------------------
> [2021-06-14 15:47:56.640] [EAXEFX] [I]
> [2021-06-14 15:47:56.640] [EAXEFX] [I] Load AL driver.
> [2021-06-14 15:47:56.640] [EAXEFX] [I] Try to load a driver "eaxefx_driver.dll".
> [2021-06-14 15:47:56.640] [EAXEFX] [E] [WIN32_SHARED_LIBRARY] ::LoadLibraryW failed.
> [2021-06-14 15:47:56.640] [EAXEFX] [I] Try to load a driver "dsoal-aldrv.dll".
> [2021-06-14 15:47:56.641] [EAXEFX] [E] [WIN32_SHARED_LIBRARY] ::LoadLibraryW failed.
> [2021-06-14 15:47:56.641] [EAXEFX] [I] Try to load a driver "soft_oal.dll".
> [2021-06-14 15:47:56.641] [EAXEFX] [I] Load AL symbols (AL 1.1; ALC 1.1; EFX 1.0).
> [2021-06-14 15:47:56.641] [EAXEFX] [I] Create EAXX.
> [2021-06-14 15:47:56.664] [EAXEFX] [I] Open device "OpenAL Soft".
> [2021-06-14 15:48:00.426] [EAXEFX] [E] EAXSet failed.
> [2021-06-14 15:48:00.426] [EAXEFX] [E] [EAXX_CONTEXT] EFX extension not found.
> [2021-06-14 15:48:20.624] [EAXEFX] [E] EAXSet failed.
> [2021-06-14 15:48:20.624] [EAXEFX] [E] [EAXX] Context not initialized.
> [2021-06-14 15:48:20.878] [EAXEFX] [E] EAXSet failed.
> [2021-06-14 15:48:20.878] [EAXEFX] [E] [EAXX] Context not initialized.
> [2021-06-14 15:48:21.680] [EAXEFX] [E] EAXSet failed.
> [2021-06-14 15:48:21.680] [EAXEFX] [E] [EAXX] Context not initialized.

**Comment by bibendovsky** [comment]
Sorry, can't reproduce.
Tested with OpenAL Soft v1.21.1.

Try to test `soft_oal.dll` with `openal-info32.exe` (bundled with OpenAL Soft).
Copy `soft_oal.dll` somewhere and rename to `OpenAL32.dll`.
Than run here `openal-info32.exe` from command-line.
Ensure the output of `openal-info32.exe` contains `ALC_EXT_EFX` (ALC extensions) and `EFX version` is `1.0`.
You can also attach a file with output here.

**Comment by vlad54rus** [comment]
Was using OpenAL Soft 1.21.0, updating to 1.21.1 resolved the issue.
But why it isn't compatible with the earlier version?

**Comment by mirh** [comment]
https://github.com/kcat/openal-soft/commit/27e8807a5b9ff1ced122834d70ea6612060d2cf1
https://github.com/kcat/openal-soft/issues/497 ?
