### ISSUE TITLE
Linux support possible

### ISSUE THREAD

**Issue by bjb43** [bibendovsky/eaxefx#22]
Hi, 
first let me thank you for your work :)! As you load openalsoft which also works fantastically on linux: Would it be possible to provide precompiled linux library? I'm asking because I want to test if the native UT2004 port, which uses OpenAL, could actually use OpenAL + EAX on linux once your library were provided.
Thanks!

**Comment by bibendovsky** [comment]
Brief search for EAX extension strings ("EAX3.0", "EAX4.0", .etc) inside the binaries for Linux (`ut2004-bin`, `ut2004-bin-linux-amd64`) gives nothing.
I doubt that Linux version uses EAX API.

**Comment by bjb43** [comment]
Thans a lot for looking into this, then it's surely not worth the effort. Out of curiosity: what program do you use to analyze the binaries? Thanks!

PS: It is also not using EFX, right?

**Comment by bibendovsky** [comment]
> Out of curiosity: what program do you use to analyze the binaries?

[Total Commander](https://www.ghisler.com/)'s internal viewer. It's enough to search for strings.

> PS: It is also not using EFX, right?

Nope. There is no string `ALC_EXT_EFX` inside the binaries.
Also, EFX was introduced much later (around year 2009) after the patch release (2005).

**Comment by bjb43** [comment]
Thanks for your response!

**Comment by mirh** [comment]
Aside of that anyway
Wouldn't it be time for this to be merged back into upstream openal-soft?

**Comment by bibendovsky** [comment]
> Wouldn't it be time for this to be merged back into upstream openal-soft?

Yes, I'll release v1.0.6 and begin to make the code compatible as much as possible with OpenAL Soft's code base (C++ standard, .etc).
