### ISSUE TITLE
Quake 4 doesn't update sound position fast enough?

### ISSUE THREAD

**Issue by jan-kleks** [bibendovsky/eaxefx#23]
Hello,

I Drink Lava mentions this issue in the description of [the video demonstrating 3D sound in Quake 4](https://www.youtube.com/watch?v=Vdn4XTpPqrg): "The one problem with Quake 4 with OpenAL Soft seems to be that it doesn't update sound position fast enough. This is a problem I've had with a couple games, but none that sounded as great as Quake 4. Reducing the period size helps somewhat, but you can still hear it if you do a 180 turn fast enough."

You worked on the occlusion fix, so maybe this is something that could be potentially fixed as well?

Regards

**Comment by bibendovsky** [comment]
How fast it should be?

The game is updated at a fixed 60 Hz tick.
There is no cvar to change the tick rate, it's hardcoded constant.
Without source code it's hard to accomplish.
I can only suggest to tweak `com_asyncAudio` cvar.

**Comment by jan-kleks** [comment]
Maybe [this](https://github.com/Reddragoon244/Quake-4-Source-Code/blob/master/sound/sound.h) could help?

**Comment by bibendovsky** [comment]
It won't.
This file is a part of client-side code (public SDK).
You need the engine code to make changes.
