### ISSUE TITLE
Install both eaxefx_bin_win32 AND eaxefx_bin_win64?

### ISSUE THREAD

**Issue by Bamajon1974** [bibendovsky/eaxefx#25]
Do I need to install both eaxefx_bin_win32_v1_0_6.zip AND eaxefx_bin_win64_v1_0_6.zip binary files? The original Host OpenAL installs OpenAL32 files in both %systemroot%\system32 and %systemroot%\SysWOW64 folders so I am assuming both eaxefx 32 and 64 bit files need copying, right? 
Please correct me if I am wrong. System32 is for 64 bit files and SysWOW64 is for 32 bit files, right? So the OpenAL32.dll from eaxefx_bin_win64_v1_0_6.zip goes in %systemroot%\system32 \ folder
and OpenAL32.dll from eaxefx_bin_win32_v1_0_6.zip goes in %systemroot%\SysWOW64\ folder, right? 

Thanks!

**Comment by mirh** [comment]
Yes. 
But take note that they are independent of each other. 
So unless you have 64-bit openal games, you'd usually just need the one in SysWOW64. 
(also remember that if the game ships with its own version of openal32, it will override the system one)

**Comment by Bamajon1974** [comment]
Understood. Thank you!
