### ISSUE TITLE
EAX enable in splinter cell

### ISSUE THREAD

**Issue by UserGit-2021** [bibendovsky/eaxefx#26]
![изображение](https://user-images.githubusercontent.com/91757058/175668572-9b5970e2-fb4b-4947-a0df-8369973dc174.png)
How enable EAX in splinter cell?

**Comment by mirh** [comment]
With dsoal man, you are in the totally wrong repository
https://github.com/kcat/dsoal

**Comment by Kappa971** [comment]
The Steam version of Splinter Cell has removed EAX (I think it's version 1.03). You need the original Splinter Cell DVD with patch 1.02 and DSOAL+OpenAL Soft or ALchemy.

**Comment by UserGit-2021** [comment]
> The Steam version of Splinter Cell has removed EAX (I think it's version 1.03). You need the original Splinter Cell DVD with patch 1.02 and DSOAL+OpenAL Soft or ALchemy.

Wrong. Steam version supports EAX. Solved the problem. You need to run as administrator for EAX to work.
GOG.com and Uplay releases have broken support for EAX Advanced HD, falling back to EAX 2.0.

**Comment by mirh** [comment]
I only have the later splinter cell digitally, so I cannot really chime in. 
..But are you sure "run as administrator to work" isn't you using XP compatibility mode?

**Comment by UserGit-2021** [comment]
> I only have the later splinter cell digitally, so I cannot really chime in. ..But are you sure "run as administrator to work" isn't you using XP compatibility mode?

I do not use compatibility mode, only on behalf of the administrator.

**Comment by mirh** [comment]
Mhh.. that's very odd. There's no reason that should affect anything. 
Even if the game failed to write whatever the setting, it should still be saved by redirection to virtualstore.
