### ISSUE TITLE
EAX OpenAL Extension в игре S.T.A.L.K.E.R.

### ISSUE THREAD

**Issue by Hozar2002** [bibendovsky/eaxefx#27]
Здравствуйте. Запускал вашу библиотеку в игре S.T.A.L.K.E.R. Зов Припяти. Работает хорошо, искажений по звуку нет, и нет багов, присущему нативному сталкерскому EAX (которые, возможно, случаются из-за встроенной звуковой карты) - треск при смене EAX зон. Но есть одна проблема. Игра намертво зависат при завершении, и закрывается только через диспетчер задач. Смог костыльно исправить это, заинжектив в вашу библиотеку свою с таким вот хуком.
`PMSG pmsg;`
`pmsg = (PMSG)lParam;`
`if (code < 0) return CallNextHookEx(hHookQuit, code, wParam, lParam);`
`else if (pmsg->message == WM_QUIT) TerminateProcess(GetCurrentProcess(), 0x0);`
Собственно это помогло, но факт остался. Будут ли попытки пофиксить это?

**Comment by bibendovsky** [comment]
> Собственно это помогло, но факт остался. Будут ли попытки пофиксить это?

Нет, не имеет смысла.
С тех пор, как обёртка была интегрирована в [OpenAL Soft](https://github.com/kcat/openal-soft), отпала необходимость в дальнейшем развитии проекта (разве что, только приложение `eaxefx_app_patcher.exe`).
