### ISSUE TITLE
Unreal 2 !

### ISSUE THREAD

**Issue by donizettilorenzo** [bibendovsky/eaxefx#3]
Man, the wrapper IS WORKING! It's awesome!
Unreal 2 can use EAX only through OpenAL "native" interface and NOT DirectSound like UT 2004, so you've solved a 18 years old problem :D (DSOAL has no use here!)

Still there are some little issues! Can you test personally Unreal 2 and hear them by yourself (->footsteps and water sounds in the Severnaya level when you load a savegame on the dam)? The Unreal Anthology package release is already patched (and Steam release too, maybe) to the lastest version!
No issue with an old and glorious Audigy 2 ZS!

But man, you did finally free us from Creative! (X-Fi cards, Titanium apart, do not work correctly with old OpenAL games and the Audigy 2 can't be installed on modern systems).

**Comment by donizettilorenzo** [comment]
Here's a video of the (sound) problem: https://www.mediafire.com/file/ar7wg2n6ff9ofdh/Unreal2+2021+04+19+02+36+55+821-1.mkv/file

EDIT: it's an OpenAL Soft problem, not of your wrapper!

**Comment by bibendovsky** [comment]
Seems it's Unreal's problem.
Try to set channels to 30 or less in audio options.
