### ISSUE TITLE
No Reverb in Doom 3?

### ISSUE THREAD

**Issue by SystemShocker287** [bibendovsky/eaxefx#32]
Good Evening. I'm having this weird issue with Doom 3 where I have properly installed EAXEFX and I can turn EAX on...but there doesn't seem to be any reverb in-game. 

[eaxefx_log.txt](https://github.com/bibendovsky/eaxefx/files/9602975/eaxefx_log.txt)

here is the log from the last time I played if you needed it.

**Comment by bibendovsky** [comment]
You are using OpenAL Soft v1.22.2 which already supports EAX extension.
Rename `soft_oal.dll` to `OpenAL32.dll` or set Doom 3 CVAR `s_libOpenAL` to `soft_oal.dll` and restart the game.
Don't use the wrapper since it will not be maintaned anymore.
