### ISSUE TITLE
idSoundCache: error unloading data from OpenAL hardware buffer в RoE с патчером

### ISSUE THREAD

**Issue by riddimmdfk** [bibendovsky/eaxefx#33]
Здравствуйте! Наткнулся однажды на видео стримера, который проходит Doom 3 и разные модификации к нему. В этом видео он показывает, что у него была ошибка "idSoundCache: error unloading data from OpenAL hardware buffer" в модификации "In Hell". Единственное решение, которое он нашёл, это было быстрое сохранение перед выходом с уровня, быстрая загрузка и последующий выход из уровня. Видео: https://youtu.be/z_u3vxmvi-U. Я посоветовал ему Ваш патчер, и он ему помог. Так же раньше у него вылетал один из уровней основной кампании, патчер так же решил его проблему. К сожалению, при проверке Resurrection of Evil у него всё равно происходит вылет с этой ошибкой: https://youtu.be/F818C9i9b30?t=2895. Он пробовал так же использовать все 4 исправления, но безрезультатно. Что можете сказать по этому поводу? Почему именно в RoE вылеты имеют место быть?

**Comment by bibendovsky** [comment]
Попробуйте значение ноль для переменной `com_purgeAll`.
Скорее всего, в патче я не учитываю потоковые источники OpenAL, только статичные.
Из-за этого может и вылетает эта ошибка.
Попробую проверить.

**Comment by riddimmdfk** [comment]
> Попробуйте значение ноль для переменной `com_purgeAll`.

Это помогло, спасибо! Нужно ли мне закрывать этот вопрос как решённый, или здесь будет выложена ссылка на возможное обновление патчера?

**Comment by bibendovsky** [comment]
> Нужно ли мне закрывать этот вопрос как решённый, или здесь будет выложена ссылка на возможное обновление патчера?

Закрывать пока не надо.
Надо разобраться почему так происходит.

**Comment by bibendovsky** [comment]
Добавил (тестовую сборку)[https://github.com/bibendovsky/idt4/pull/3#issuecomment-1321222231] в виде исполняемого файла `doom3.exe`.
Включает в себя все патчи для Doom 3, что и eaxefx (кроме "Scales down volume of all sounds").

**Comment by bibendovsky** [comment]
Обновил патчер.
[eaxefx_app_patcher-v1.0.9-9079d1385f7bb658a1ac398e744f5d45d6abba83.zip](https://github.com/bibendovsky/eaxefx/files/10136254/eaxefx_app_patcher-v1.0.9-9079d1385f7bb658a1ac398e744f5d45d6abba83.zip)
