### ISSUE TITLE
[DOOM3] Fix scaling down volume of sounds

### ISSUE THREAD

**Issue by Kappa971** [bibendovsky/eaxefx#36]
As previously discussed, Doom 3 suffers from a rather strange issue when turning down the master volume in the game menu. 
Some effects or weapons will be louder than others, the volume level of the sounds will be different/wrong than when the master volume is set to 0db (here I think it's explained in a more technical way: https://github.com/dhewm/dhewm3/issues/326#issuecomment-1366833004).
This seems to fix the problem: https://github.com/dhewm/dhewm3/commit/4567f265392b5ab95a335f8896ff003a743990e4

**Comment by bibendovsky** [comment]
Updated patch application.
[eaxefx_app_patcher_bin_win32_v1.0.4-ac28b441e32c95b6e3f951b3c2d329477b01d6fa.zip](https://github.com/bibendovsky/eaxefx/files/10376447/eaxefx_app_patcher_bin_win32_v1.0.4-ac28b441e32c95b6e3f951b3c2d329477b01d6fa.zip)
[eaxefx_app_patcher_bin_win64_v1.0.4-ac28b441e32c95b6e3f951b3c2d329477b01d6fa.zip](https://github.com/bibendovsky/eaxefx/files/10376448/eaxefx_app_patcher_bin_win64_v1.0.4-ac28b441e32c95b6e3f951b3c2d329477b01d6fa.zip)

This version may not be compatible with previous one.
Use fresh copy of DOOM3 v1.3.1 executable file to patch.

**Comment by Kappa971** [comment]
Thanks @bibendovsky, you made this game playable again!
