### ISSUE TITLE
Can't enumerate on winxp

### ISSUE THREAD

**Issue by jaysharp29** [bibendovsky/eaxefx#5]
The minimum os requirements state winxp sp3, however in my retro build using winxp sp3 the router provides no enumeration through Alcaps viewer nor does it route to soft_oal or any creative  openal dll after a rename.  Openal soft works on it's own.

Does this actually work on xp?

**Comment by mirh** [comment]
https://github.com/kcat/dsoal/issues/22

**Comment by jaysharp29** [comment]
Not sure how this answers my question, as the eaxefx router is stated to work on xpsp3, and doesn't rely on dsoal.  Unless I'm misunderstanding how this router works.  Soft_oal is one of the driver names the router works with, and soft_oal works on winxp.

**Comment by bibendovsky** [comment]
The only problem I encounter is crash of `ALCapsViewer32.exe` and `EnumerateWin32.exe` from [OpenAL tools](https://community.pcgamingwiki.com/files/file/625-openal-tools/).

Here is result of fix:
![image](https://user-images.githubusercontent.com/1597301/120358817-9a903580-c30f-11eb-95c9-71d6aed752e1.png)
![image](https://user-images.githubusercontent.com/1597301/120358885-b4317d00-c30f-11eb-963d-2b2113c1a313.png)

**Comment by bibendovsky** [comment]
Fix for crash.
[eaxefx_bin_win32_v1_0_6_636b695.zip](https://github.com/bibendovsky/eaxefx/files/6578250/eaxefx_bin_win32_v1_0_6_636b695.zip)

**Comment by jaysharp29** [comment]
Thank you. I also experienced a crash in quake 4 using this router, so hopefully this resolved that as well (on winxp).
